module.exports = [
    {
      id: 1,
      captainName: "Picard",
      title: "Courage",
      post: "Courage can be an emotion too.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 100,
    },
    {
      id: 2,
      captainName: "Ahab",
      title: "Whale",
      post: "By heavens man, we are turned round and round in this world, like yonder windlass, and fate is the handspike.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 20,
    },
    {
      id: 3,
      captainName: "Sarah Lance",
      title: "Vandal Savage",
      post: "I’d tell you to go to hell, but you’d probably just feel at home there.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 0,
    },
    {
      id: 4,
      captainName: "Ahab",
      title: "Insolence",
      post: "I don't give reasons. I give orders!",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 100,
    },
    {
      id: 5,
      captainName: "Sarah Lance",
      title: "Ava",
      post: "Ava's the kind of girl that you take home to your parents, and I am the kind you take to an exorcism",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 0,
    },
    {
      id: 6,
      captainName: "Ahab",
      title: "What is sleep?",
      post: "Sleep? That bed is a coffin, and those are winding sheets. I do not sleep, I die.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 5,
    },
    {
      id: 7,
      captainName: "Sarah Lance",
      title: "Jonah Hex",
      post: "I know you don’t like taking orders from a woman, but you’re gonna like getting your ass kicked by one even less.",
      mistakesWereMadeToday: true,
      daysSinceLastCrisis: 0,
    },
  ];